name: Tests
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
env:
  NODE_VER: 18.x
jobs:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout the source code
      uses: actions/checkout@v3

  - name: Install & display rust toolchain
    run: |
      rustup show
      rustup component add rust-src

  - name: Check targets are installed correctly
    run: rustup target list --installed

  - name: Cache cargo
    uses: actions/cache@v3
    with:
      path: ~/.cargo
      key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
      restore-keys: |
        ${{ runner.os }}-rust

  - name: Install cargo contract
    if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
    run: |
      cargo install cargo-dylint dylint-link
      cargo install --force --locked cargo-contract

  - name: Use Node.js
    uses: actions/setup-node@v3
    with:
      node-version: ${{ env.NODE_VER }}

  - name: Install swanky-cli
    run: npm install && npm install -g @astar-network/swanky-cli

  - name: Compile contracts
    run:
      swanky contract compile

  - name: Test contracts
    run:
      swanky contract test
